#!/bin/sh

# Output filename read from command line or in the file "name.in"
if [ "$1" != "" ]; then
	file="$1"
else
	if [ -f "name.in" ]; then
		file=`cat name.in`
	else
		echo "Name of the output file to be read"
		read file
	fi
fi

# If output file does not exist, add .out suffix
if [ ! -f "$file" ]; then
	file=`echo "$file" | sed -e "/.out/!s/$/.out/"`
fi

# Post-process output file
if [ -f "$file" ]; then
	T_file=`echo "$file" | sed -e "s/.out$/.T/"`
	grep "Temp\ in" $file | sed -e "/\*Temp/s/\*Temp\ instantanee\ =//" > "$T_file"

	Ec_file=`echo "$file" | sed -e "s/.out$/.Ec/"`
	grep "Ec =" $file | sed -e "/\*Ec/s/\*Ec\ =//" > "$Ec_file"

	Eelec_file=`echo "$file" | sed -e "s/.out$/.Eelec/"`
	grep "Eelec =" $file | sed -e "/\*Eelec/s/\*Eelec\ =//" > "$Eelec_file"
	if [ -s $Eelec_file ]
	then
        echo 
	else
	rm -f $Eelec_file
	fi

	Telec_file=`echo "$file" | sed -e "s/.out$/.Telec/"`
	grep "Telec =" $file | sed -e "/\*Telec/s/\*Telec\ =//" > "$Telec_file"
	if [ -s $Telec_file ]
	then
        echo 
	else
	rm -f $Telec_file
	fi

	TempEP_file=`echo "$file" | sed -e "s/.out$/.TempEP/"`
	grep "TempEP =" $file | sed -e "/\*TempEP/s/\*TempEP\ =//" > "$TempEP_file"
	if [ -s $TempEP_file ]
	then
        echo 
	else
	rm -f $TempEP_file
	fi

	IE_E_file=`echo "$file" | sed -e "s/.out$/.IE_E/"`
	grep "IE_Et =" $file | sed -e "/\*IE_Et/s/\*IE_Et\ =//" > "$IE_E_file"
	if [ -s $IE_E_file ]
	then
        echo 
	else
	rm -f $IE_E_file
	fi

	Epot_file=`echo "$file" | sed -e "s/.out$/.Epot/"`
	grep "Epot =" $file | sed -e "/\*Epot/s/\*Epot\ =//" > "$Epot_file"

	Etot_file=`echo "$file" | sed -e "s/.out$/.Etot/"`
	grep "Etot =" $file | sed -e "/\*Etot/s/\*Etot\ =//" > "$Etot_file"

	Etot_complete_file=`echo "$file" | sed -e "s/.out$/.Etot_complete/"`
	grep "Etot_complete =" $file | sed -e "/\*Etot_complete/s/\*Etot_complete\ =//" > "$Etot_complete_file"
	if [ -s $Etot_complete_file ]
	then
        echo 
	else
	rm -f $Etot_complete_file
	fi

	volume_file=`echo "$file" | sed -e "s/.out$/.volume/"`
	grep "volume " $file | sed -e /\*volume/s/\*volume// > $volume_file
	if [ -s $volume_file_file ]
	then
        echo 
	else
	rm -f $volume_file
	fi

	P_file=`echo "$file" | sed -e "s/.out$/.P/"`
	grep "Pression =" $file | sed -e "/\*Pression/s/\*Pression\ =//" > "$P_file"
	if [ -s $P_file ]
	then
        echo 
	else
	rm -f $P_file
	fi

	zl_a_file=`echo "$file" | sed -e "s/.out$/.zl_a/"`
	grep "l_a" $file | sed -e /\*l_a/s/\*l_a\,m\// > $zl_a_file
	if [ -s $zl_a_file ]
	then
        echo 
	else
	rm -f $zl_a_file
	fi

	zl_b_file=`echo "$file" | sed -e "s/.out$/.zl_b/"`
	grep "l_b" $file | sed -e /\*l_b/s/\*l_b\,m\// > $zl_b_file
	if [ -s $zl_b_file ]
	then
        echo 
	else
	rm -f $zl_b_file
	fi

	zl_c_file=`echo "$file" | sed -e "s/.out$/.zl_c/"`
	grep "l_c" $file | sed -e /\*l_c/s/\*l_c\,m\// > $zl_c_file
	if [ -s $zl_c_file ]
	then
        echo 
	else
	rm -f $zl_c_file
	fi

	ang_bc_file=`echo "$file" | sed -e "s/.out$/.ang_bc/"`
	grep "ang_bc" $file | sed -e /\*ang_bc/s/\*ang_bc\,m\// > $ang_bc_file
	if [ -s $ang_bc_file ]
	then
        echo 
	else
	rm -f $ang_bc_file
	fi

	ang_ca_file=`echo "$file" | sed -e "s/.out$/.ang_ca/"`
	grep "ang_ca" $file | sed -e /\*ang_ca/s/\*ang_ca\,m\// > $ang_ca_file
	if [ -s $ang_ca_file ]
	then
        echo 
	else
	rm -f $ang_ca_file
	fi

	ang_ab_file=`echo "$file" | sed -e "s/.out$/.ang_ab/"`
	grep "ang_ab" $file | sed -e /\*ang_ab/s/\*ang_ab\,m\// > $ang_ab_file
	if [ -s $ang_ab_file ]
	then
        echo 
	else
	rm -f $ang_ab_file
	fi

	sigma_file=`echo "$file" | sed -e "s/.out$/.sigma/"`
	/bin/echo -e "#s11\t\ts22\t\ts33\t\ts23\t\ts13\t\ts12" > $sigma_file
	grep "[123] sigma total" $file | awk '$1==1 {printf $(NF-2) "\t" $(NF-1) "\t" $(NF) "\t"} \
		$1==2 {printf $(NF-1)"\t "$(NF) "\t"} \
		$1==3 {printf $(NF)"\n"}' | awk '{print $1 "\t" $4 "\t" $6 "\t" $5 "\t" $3 "\t" $2}' >> $sigma_file
	if [ -s $sigma_file ]
	then
        echo 
	else
	rm -f $sigma_file
	fi


	Kcell_file=`echo "$file" | sed -e "s/.out$/.Kcell/"`
	grep "Kcell" $file | sed -e "/\*Kcell/s/\*Kcell\ =//" -e "s/eV   (//" -e "s/K)//"	> "$Kcell_file"
	if [ -s $Kcell_file ]
	then
        echo 
	else
	rm -f $Kcell_file
	fi

	KNose_file=`echo "$file" | sed -e "s/.out$/.KNose/"`
	grep "KNose" $file | sed -e "/\*KNose/s/\*KNose\ =//" -e "s/eV   (//" -e "s/K)//"	> "$KNose_file"
	if [ -s $KNose_file ]
	then
        echo 
	else
	rm -f $KNose_file
	fi


	fNose_file=`echo "$file" | sed -e "s/.out$/.fNose/"`
	grep "\*fNose" $file | sed -e "/\*fNose/s/\*fNose\ =//" 	> "$fNose_file"
	if [ -s $fNose_file ]
	then
        echo 
	else
	rm -f $fNose_file
	fi

	zHoover_file=`echo "$file" | sed -e "s/.out$/.zHoover/"`
	grep "\*zHoover" $file | sed -e "/\*zHoover/s/\*zHoover\ =//" 	> "$zHoover_file"
	if [ -s $zHoover_file ]
	then
        echo 
	else
	rm -f $zHoover_file
	fi

	Htot_Hoover_file=`echo "$file" | sed -e "s/.out$/.Htot_Hoover/"`
	grep "\*Htot_Hoover" $file | sed -e "/\*Htot_Hoover/s/\*Htot_Hoover\ =//" 	> "$Htot_Hoover_file"
	if [ -s $Htot_Hoover_file ]
	then
        echo 
	else
	rm -f $Htot_Hoover_file
	fi

	# Plot outputs
	#    Temperature
	gnuplot -persist << EOF
	set ylabel 'T (K)'
	set xlabel '# iter'
	plot "$T_file" u 1:3 t "Atomes" w l
EOF
	#    Etot
	gnuplot -persist << EOF
	set ylabel 'Etot'
	set xlabel '# iter'
	plot "$Etot_file" u 1:3 t "Atomes" w l
EOF
	#    Ec
	gnuplot -persist << EOF
	set ylabel 'Ec'
	set xlabel '# iter'
	plot "$Ec_file" u 1:3 t "Atomes" w l
EOF
	#    Epot
	gnuplot -persist << EOF
	set ylabel 'Epot'
	set xlabel '# iter'
	plot "$Epot_file" u 1:3 t "Atomes" w l
EOF
	#    TempEP
	gnuplot -persist << EOF
	set ylabel 'TempEP'
	set xlabel '# iter'
	plot "$TempEP_file" u 1:3 t "Atomes" w l
EOF
	#    IEtot
	gnuplot -persist << EOF
	set ylabel 'EeiTOT'
	set xlabel '# iter'
	plot "$IE_E_file" u 1:3 t "Atomes" w l
EOF
	#    Eelec
	gnuplot -persist << EOF
	set ylabel 'Eelec'
	set xlabel '# iter'
	plot "$Eelec_file" u 1:3 t "Atomes" w l
EOF
	#    Telec
	gnuplot -persist << EOF
	set ylabel 'Telec'
	set xlabel '# iter'
	plot "$Telec_file" u 1:3 t "Atomes" w l
EOF
	#    simulation box angles
	gnuplot -persist << EOF
	set ylabel 'angle (°)'
	set xlabel '# iter'
	plot "$ang_ab_file" u 1:3 t "a^b" w l,\
	     "$ang_bc_file" u 1:3 t "b^c" w l,\
	     "$ang_ca_file" u 1:3 t "c^a" w l
EOF
	#    simulation box dimensions
	gnuplot -persist << EOF
	set ylabel 'l (A)'
	set xlabel '# iter'
	plot "$zl_a_file" u 1:3 t "a" w l,\
	     "$zl_b_file" u 1:3 t "b" w l,\
	     "$zl_c_file" u 1:3 t "c" w l
EOF
	#    simulation box volume
	gnuplot -persist << EOF
	set ylabel 'V (A³)'
	set xlabel '# iter'
	plot "$volume_file" u 1:3 t "" w l
EOF
	#    Pressure
	gnuplot -persist << EOF
	set ylabel 'P (kbar)'
	set xlabel '# iter'
	plot "$P_file" u 1:3 t "" w l
EOF
	# Stress
	gnuplot -persist << EOF
	set ylabel 'sigma (kbar)'
	set xlabel '# iter'
	plot "$sigma_file" u 0:1 t 's11' w l,\
	     "$sigma_file" u 0:2 t 's22' w l,\
	     "$sigma_file" u 0:3 t 's33' w l,\
	     "$sigma_file" u 0:4 t 's23' w l,\
	     "$sigma_file" u 0:5 t 's13' w l,\
	     "$sigma_file" u 0:6 t 's12' w l
EOF
	# Box kinetic energy
	gnuplot -persist << EOF
	set ylabel 'Kcell (eV)'
	set xlabel '# iter'
	plot "$Kcell_file" u 1:3 t "" w l
EOF
	# Thermostat f value
	gnuplot -persist << EOF
	set ylabel 'fNose (eV)'
	set xlabel '# iter'
	plot "$fNose_file" u 1:3 t "" w l
EOF

	# Thermostat kinetic energy
	gnuplot -persist << EOF
	set ylabel 'KNose (eV)'
	set xlabel '# iter'
	plot "$KNose_file" u 1:3 t "" w l
EOF
		
		
	# Thermostat kinetic energy
	gnuplot -persist << EOF
	set ylabel 'zHoover (eV)'
	set xlabel '# iter'
	plot "$zHoover_file" u 1:3 t "" w l
EOF
		
	# Thermostat kinetic energy
	gnuplot -persist << EOF
	set ylabel 'Htot_Hoover (eV)'
	set xlabel '# iter'
	plot "$Htot_Hoover_file" u 1:3 t "" w l
EOF
		
else
	echo "file $file does not exist"
	return
fi

