#!/bin/csh -f

rm test_proc.dat
rm donnes_graph.dat
rm jt3.out

@ index=1
while($index<512)

echo ${index}
cat >decoup.dat <<EOF
$index
EOF


/home/croc/NDM/bin/rundm90_seq_decoup >> jt3.out

@ index++
grep valeur jt3.out > test_proc.dat 
grep equilibrage jt3.out > equilibrage.dat 
grep locmin jt3.out > locSfront_proc.dat 
grep "conf\." jt3.out > echanges_proc.dat 

end



/usr/bin/gnuplot jt2.gp



