; Created by: Jmol 14.3.13_2015.03.23  2015-03-23 07:22
; Creation date: jeu., 3 déc. 2015 13:43:34 +0100
; File created: /home/wesley/Documents/resume/figures/v3.pov (59378 bytes)


; Jmol state: (embedded in input file)
Input_File_Name=v3.pov
Output_to_File=true
Output_File_Type=N
Output_File_Name=v3.pov.png
Width=879
Height=548
Antialias=true
Antialias_Threshold=0.1
Display=true
Pause_When_Done=true
Warning_Level=5
Verbose=false
