include(FindPackageHandleStandardArgs)

# order matters
set(LAMMPS_MODULE_NAME lammps_mpi)
set(LAMMPS_DEFINITIONS "" PARENT_SCOPE)

find_package(PkgConfig QUIET)
if (${PKG_CONFIG_FOUND})
    pkg_check_modules(LAMMPS "lib${LAMMPS_MODULE_NAME}")
#    set(LAMMPS_LIBRARIES ${PKGC_MKL_LIBRARIES})
#    set(LAMMPS_LINK_LIBRARIES ${PKGC_MKL_LINK_LIBRARIES})
#    set(LAMMPS_LIBRARY_DIRS ${PKGC_MKL_LIBRARY_DIRS})
#    set(LAMMPS_LDFLAGS ${PKGC_MKL_LDFLAGS})
#    set(LAMMPS_CFLAGS ${PKGC_MKL_CFLAGS})
#    set(LAMMPS_INCLUDE_DIRS ${PKGC_MKL_INCLUDE_DIRS})
#    set(LAMMPS_VERSION ${PKGC_MKL_VERSION})
endif()

if (NOT LAMMPS_FOUND) 
    string(REPLACE ":" ";" TMP_LD_PATH $ENV{LD_LIBRARY_PATH})
    find_library(TMP_PATH_TO_LIBRARY ${LAMMPS_MODULE_NAME} HINTS ${TMP_LD_PATH})
    if (NOT TMP_PATH_TO_LIBRARY STREQUAL "TMP_PATH_TO_LIBRARY-NOTFOUND")
        cmake_path(REMOVE_FILENAME TMP_PATH_TO_LIBRARY )
        list(APPEND LAMMPS_LIBRARY_DIRS ${TMP_PATH_TO_LIBRARY} )
        list(APPEND LAMMPS_INCLUDE "${TMP_PATH_TO_LIBRARY}/../include" )
        
    endif()
    list(APPEND LAMMPS_LIBRARIES "${LAMMPS_MODULE_NAME}")
    list(APPEND LAMMPS_DEFINITIONS "LAMMPS_SMALLBIG")
endif()



# required variables for find_package()
find_package_handle_standard_args( LAMMPS 
    REQUIRED_VARS LAMMPS_LIBRARY_DIRS LAMMPS_LIBRARIES 
    VERSION_VAR LAMMPS_VERSION
)
# optionnal output variables :
set(LAMMPS_LINK_LIBRARIES ${LAMMPS_LINK_LIBRARIES} PARENT_SCOPE)
set(LAMMPS_CFLAGS ${LAMMPS_CFLAGS} PARENT_SCOPE)
set(LAMMPS_LDFLAGS ${LAMMPS_LDFLAGS} PARENT_SCOPE)
set(LAMMPS_INCLUDE_DIRS ${LAMMPS_INCLUDE_DIRS} PARENT_SCOPE)
