#!/bin/sh

# Output filename read from command line or in the file "name.in"
if [ "$1" != "" ]; then
	file="$1"
else
	if [ -f "name.in" ]; then
		file=`cat name.in`
	else
		echo "Name of the output file to be read"
		read file
	fi
fi

# If output file does not exist, add .out suffix
if [ ! -f "$file" ]; then
	file=`echo "$file" | sed -e "/.out/!s/$/.out/"`
fi

# Post-process output file
if [ -f "$file" ]; then
	T_file=`echo "$file" | sed -e "s/.out$/.T/"`
	grep "Temp\ in" $file | sed -e "/\*Temp/s/\*Temp\ instantanee\ =//" > "$T_file"
	Ec_file=`echo "$file" | sed -e "s/.out$/.Ec/"`
	grep "Ec =" $file | sed -e "/\*Ec/s/\*Ec\ =//" > "$Ec_file"
	Epot_file=`echo "$file" | sed -e "s/.out$/.Epot/"`
	grep "Epot =" $file | sed -e "/\*Epot/s/\*Epot\ =//" > "$Epot_file"
	Etot_file=`echo "$file" | sed -e "s/.out$/.Etot/"`
	grep "Etot =" $file | sed -e "/\*Etot/s/\*Etot\ =//" > "$Etot_file"
	Etot_complete_file=`echo "$file" | sed -e "s/.out$/.Etot_complete/"`
	grep "Etot_complete =" $file | sed -e "/\*Etot_complete/s/\*Etot_complete\ =//" > "$Etot_complete_file"
	volume_file=`echo "$file" | sed -e "s/.out$/.volume/"`
	grep "volume " $file | sed -e /\*volume/s/\*volume// > $volume_file
	P_file=`echo "$file" | sed -e "s/.out$/.P/"`
	grep "Pression =" $file | sed -e "/\*Pression/s/\*Pression\ =//" > "$P_file"
	zl_a_file=`echo "$file" | sed -e "s/.out$/.zl_a/"`
	grep "l_a" $file | sed -e /\*l_a/s/\*l_a\,m\// > $zl_a_file
	zl_b_file=`echo "$file" | sed -e "s/.out$/.zl_b/"`
	grep "l_b" $file | sed -e /\*l_b/s/\*l_b\,m\// > $zl_b_file
	zl_c_file=`echo "$file" | sed -e "s/.out$/.zl_c/"`
	grep "l_c" $file | sed -e /\*l_c/s/\*l_c\,m\// > $zl_c_file
	ang_bc_file=`echo "$file" | sed -e "s/.out$/.ang_bc/"`
	grep "ang_bc" $file | sed -e /\*ang_bc/s/\*ang_bc\,m\// > $ang_bc_file
	ang_ca_file=`echo "$file" | sed -e "s/.out$/.ang_ca/"`
	grep "ang_ca" $file | sed -e /\*ang_ca/s/\*ang_ca\,m\// > $ang_ca_file
	ang_ab_file=`echo "$file" | sed -e "s/.out$/.ang_ab/"`
	grep "ang_ab" $file | sed -e /\*ang_ab/s/\*ang_ab\,m\// > $ang_ab_file
	sigma_file=`echo "$file" | sed -e "s/.out$/.sigma/"`
	/bin/echo -e "#s11\t\ts22\t\ts33\t\ts23\t\ts13\t\ts12" > $sigma_file
	grep "[123] sigma total" $file | awk '$1==1 {printf $(NF-2) "\t" $(NF-1) "\t" $(NF) "\t"} \
		$1==2 {printf $(NF-1)"\t "$(NF) "\t"} \
		$1==3 {printf $(NF)"\n"}' | awk '{print $1 "\t" $4 "\t" $6 "\t" $5 "\t" $3 "\t" $2}' >> $sigma_file
	Kcell_file=`echo "$file" | sed -e "s/.out$/.Kcell/"`
	grep "Kcell" $file | sed -e "/\*Kcell/s/\*Kcell\ =//" -e "s/eV   (//" -e "s/K)//"	> "$Kcell_file"

		
else
	echo "file $file does not exist"
	return
fi

