#!/bin/bash

echo "File,CreationDate"

for file in $(git ls-files '*.F90'); do
    creation_date=$(git log --diff-filter=A --follow --format="%ad" --date=iso -- "$file" | tail -1)
    echo "$file,$creation_date"
done
