#!/bin/bash
for temp  in  *.F90 *.f Makefil* */*.F90 MAKE/* *.c *.cpp */*.c */*.cpp *.h */*.h
do 
	echo $temp
	rm -f rd
	diff   /home/croc/NDM/babar/src/$temp  $temp >rd
	diff   /home/croc/NDM/babar/src/$temp   $temp
	if  [ -s  rd ]
	then
	meld   $temp /home/croc/NDM/babar/src/$temp
	fi
	

done
