#!/bin/csh
foreach temp (`ls -1 *F90 *f Makefil* */*.F90`)
	echo $temp
	rm -f rd
	diff   $temp /volatile/home/jcrocombette/DM/codesndm/ndm2021/$temp >rd
	if  ( -s  rd )    meld /volatile/home/jcrocombette/DM/codesndm/ndm2021/$temp  $temp

end
