#!/bin/tcsh
foreach temp (`ls -1 *F90 *f Makefil* */*.F90`)
	echo $temp
	rm -f rd
	diff   $temp /mnt/c/Users/jc148490/lin/DM/codesndm/ndm2021/$temp >>rd
	if  ( -s  rd )    meld /mnt/c/Users/jc148490/lin/DM/codesndm/ndm2021/$temp  $temp

end
